version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: local
    ports:
      - 5432:5432
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - AccessKey=AKIA3U2OCHZPO6P22QJL
      - SecretKey=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
    ports:
      - 5000:80
  worker:
    build:
      context: .
      dockerfile: dockerfile.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_PASSWORD=local
      - AccessKey=AKIA3U2OCHZPO6P22QJL
      - SecretKey=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
    depends_on:
      - postgres
      - server
