FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src

COPY ./src .

RUN dotnet publish Boligmappa.Queue.Sqs.Worker/Boligmappa.Queue.Sqs.Worker.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "Boligmappa.Queue.Sqs.Worker.dll"]