version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: local
    ports:
      - 5432:5432
  server:
    build: 
      context: .
      dockerfile: dockerfile.server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
  worker:
    build: 
      context: .
      dockerfile: dockerfile.worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_PASSWORD=local
    depends_on:
      - postgres
      - server
